require "minitest/autorun"
require_relative "tachyon"

SAMPLE_INPUT = <<~INPUT
  .......S.......
  ...............
  .......^.......
  ...............
  ......^.^......
  ...............
  .....^.^.^.....
  ...............
  ....^.^...^....
  ...............
  ...^.^...^.^...
  ...............
  ..^...^.....^..
  ...............
  .^.^.^.^.^...^.
  ...............
INPUT

class TachyonLineTest < Minitest::Test
  def test_regular_beam_movement
    line = TachyonLine.new(line: ".....", beams: [ 1, 3 ])

    assert_equal [ 1, 3 ], line.calculate_beam_positions
  end

  def test_split_beam
    line = TachyonLine.new(line: ".^...", beams: [ 1, 3 ])

    assert_equal [ 0, 2, 3 ], line.calculate_beam_positions
  end

  def test_combined_beams
    line = TachyonLine.new(line: ".^.^.", beams: [ 1, 3 ])

    assert_equal [ 0, 2, 4 ], line.calculate_beam_positions
  end
end

class TachyonTest < Minitest::Test
  SAMPLE_INPUT = <<~INPUT
    .......S.......
    ...............
    .......^.......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    ...............
    ...^.^...^.^...
    ...............
    ..^...^.....^..
    ...............
    .^.^.^.^.^...^.
    ...............
  INPUT

  def setup
    @tachyon = Tachyon.new(SAMPLE_INPUT.lines)
  end

  def test_total_splits
    assert_equal 21, @tachyon.total_splits
  end

  def test_total_timelines
    assert_equal 40, @tachyon.total_timelines
  end
end
